"""Renders the dispute evidence pack as a self-contained HTML document.

The evidence pack is what Plugcut hands a party in a dispute: the immutable facts of
the introduction (parties, client, terms), the sealed attribution fingerprint, the two
signatures, the stated dispute reason, and the full timeline rebuilt from stored
timestamps. Pure string templating (no I/O), so it is trivially testable; all
user-provided values are escaped.
"""

from __future__ import annotations

from html import escape

from app.application.referrals.dtos import TimelineEntry
from app.domain.referrals.entities import Referral
from app.domain.shared.value_objects import Money

_LABELS: dict[str, dict[str, str]] = {
    "fr": {
        "title": "Dossier de preuve",
        "intro": "Pièces réunies par Plugcut pour ce deal, à présenter en cas de litige.",
        "parties": "Parties",
        "referrer": "Apporteur",
        "placed": "Personne placée",
        "client": "Client (référence confidentielle)",
        "terms": "Conditions de commission",
        "dailyRate": "TJM placé",
        "commission": "Commission",
        "duration": "Durée",
        "months": "mois",
        "monthly": "Commission mensuelle estimée",
        "total": "Total estimé sur la durée",
        "attribution": "Preuve d'attribution",
        "attributionText": "Empreinte d'attribution scellée :",
        "signatures": "Signatures",
        "dispute": "Litige déclaré",
        "disputeReason": "Motif",
        "timeline": "Historique",
        "generatedAt": "Dossier généré le",
        "footer": "Document généré par Plugcut. Projet de démonstration, sans valeur juridique.",
    },
    "en": {
        "title": "Evidence pack",
        "intro": "Records gathered by Plugcut for this deal, to present in case of dispute.",
        "parties": "Parties",
        "referrer": "Referrer",
        "placed": "Placed person",
        "client": "Client (confidential reference)",
        "terms": "Commission terms",
        "dailyRate": "Placed day rate",
        "commission": "Commission",
        "duration": "Duration",
        "months": "months",
        "monthly": "Estimated monthly commission",
        "total": "Estimated total over the duration",
        "attribution": "Attribution proof",
        "attributionText": "Sealed attribution fingerprint:",
        "signatures": "Signatures",
        "dispute": "Dispute raised",
        "disputeReason": "Reason",
        "timeline": "Timeline",
        "generatedAt": "Pack generated on",
        "footer": "Generated by Plugcut. Demonstration project, no legal value.",
    },
}

_EVENT_LABELS: dict[str, dict[str, str]] = {
    "fr": {
        "created": "Deal créé",
        "accepted_referrer": "Signé par l'apporteur",
        "accepted_placed": "Signé par la personne placée",
        "signed": "Attribution scellée",
        "activated": "Deal activé",
        "payment_recorded": "Paiement enregistré (échéance",
        "disputed": "Litige déclaré",
    },
    "en": {
        "created": "Deal created",
        "accepted_referrer": "Signed by the referrer",
        "accepted_placed": "Signed by the placed person",
        "signed": "Attribution sealed",
        "activated": "Deal activated",
        "payment_recorded": "Payment recorded (installment",
        "disputed": "Dispute raised",
    },
}


def _money(value: Money) -> str:
    return f"{value.amount} {value.currency}"


def _event_text(entry: TimelineEntry, events: dict[str, str]) -> str:
    base = events.get(entry.type, entry.type)
    if entry.type == "payment_recorded" and entry.detail:
        return f"{base} {entry.detail})"
    if entry.type in {"accepted_referrer", "accepted_placed"} and entry.detail:
        return f"{base}: {entry.detail}"
    return base


class HtmlEvidenceRenderer:
    def render(
        self,
        referral: Referral,
        *,
        referrer_email: str,
        timeline: list[TimelineEntry],
        locale: str,
    ) -> str:
        labels = _LABELS.get(locale, _LABELS["en"])
        events = _EVENT_LABELS.get(locale, _EVENT_LABELS["en"])
        terms = referral.terms
        monthly = terms.expected_amount_per_period
        total = monthly * terms.duration_months
        attribution = referral.attribution_hash or ""

        rows = "\n".join(
            f"<li><span class=\"when\">{escape(entry.at.date().isoformat())}</span>"
            f"<span class=\"what\">{escape(_event_text(entry, events))}</span></li>"
            for entry in timeline
        )

        dispute_block = ""
        if referral.dispute_reason is not None:
            raised = (referral.disputed_at or referral.created_at).date().isoformat()
            dispute_block = f"""
  <h2>{escape(labels['dispute'])}</h2>
  <dl>
    <dt>{escape(labels['generatedAt'])}</dt><dd>{escape(raised)}</dd>
    <dt>{escape(labels['disputeReason'])}</dt><dd>{escape(referral.dispute_reason)}</dd>
  </dl>"""

        return f"""<!doctype html>
<html lang="{escape(locale)}">
<head>
<meta charset="utf-8" />
<title>{escape(labels['title'])} - Plugcut</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; color: #16140f;
         max-width: 720px; margin: 2.5rem auto; padding: 0 1.5rem; line-height: 1.55; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
  .brand {{ font-weight: 700; letter-spacing: 0.05em; color: #6b7a00; }}
  .intro {{ color: #555; }}
  h2 {{ font-size: 1.05rem; margin-top: 2rem; border-bottom: 1px solid #ddd;
        padding-bottom: 0.3rem; }}
  dl {{ display: grid; grid-template-columns: 1fr 1fr; gap: 0.4rem 1rem; }}
  dt {{ color: #666; }}
  dd {{ margin: 0; font-weight: 600; }}
  .hash {{ font-family: ui-monospace, monospace; word-break: break-all; font-size: 0.85rem;
           background: #f4f1ea; padding: 0.6rem 0.8rem; border-radius: 6px; }}
  ul.timeline {{ list-style: none; padding: 0; }}
  ul.timeline li {{ display: flex; gap: 1rem; padding: 0.35rem 0;
                    border-bottom: 1px solid #eee; }}
  .when {{ font-family: ui-monospace, monospace; color: #888; min-width: 6.5rem; }}
  .what {{ font-weight: 600; }}
  footer {{ margin-top: 2.5rem; font-size: 0.78rem; color: #999; }}
</style>
</head>
<body>
  <p class="brand">PLUGCUT</p>
  <h1>{escape(labels['title'])}</h1>
  <p class="intro">{escape(labels['intro'])}</p>

  <h2>{escape(labels['parties'])}</h2>
  <dl>
    <dt>{escape(labels['referrer'])}</dt><dd>{escape(referrer_email)}</dd>
    <dt>{escape(labels['placed'])}</dt><dd>{escape(referral.placed_person_email)}</dd>
    <dt>{escape(labels['client'])}</dt><dd>{escape(referral.client_reference)}</dd>
  </dl>

  <h2>{escape(labels['terms'])}</h2>
  <dl>
    <dt>{escape(labels['dailyRate'])}</dt><dd>{escape(_money(terms.daily_rate))}</dd>
    <dt>{escape(labels['commission'])}</dt><dd>{escape(str(terms.commission))}</dd>
    <dt>{escape(labels['duration'])}</dt>
    <dd>{terms.duration_months} {escape(labels['months'])}</dd>
    <dt>{escape(labels['monthly'])}</dt><dd>{escape(_money(monthly))}</dd>
    <dt>{escape(labels['total'])}</dt><dd>{escape(_money(total))}</dd>
  </dl>

  <h2>{escape(labels['signatures'])}</h2>
  <dl>
    <dt>{escape(labels['referrer'])}</dt><dd>{escape(referral.referrer_signature or '')}</dd>
    <dt>{escape(labels['placed'])}</dt><dd>{escape(referral.placed_signature or '')}</dd>
  </dl>

  <h2>{escape(labels['attribution'])}</h2>
  <p>{escape(labels['attributionText'])}</p>
  <p class="hash">{escape(attribution)}</p>
{dispute_block}

  <h2>{escape(labels['timeline'])}</h2>
  <ul class="timeline">
{rows}
  </ul>

  <footer>{escape(labels['footer'])}</footer>
</body>
</html>"""
