"""Renders one monthly commission invoice as a self-contained HTML document.

Pure string templating (no I/O), localized FR/EN, all user-provided values escaped.
"""

from __future__ import annotations

from html import escape

from app.domain.billing.entities import CommissionInstallment
from app.domain.referrals.entities import Referral
from app.domain.shared.value_objects import Money

_LABELS: dict[str, dict[str, str]] = {
    "fr": {
        "title": "Facture de commission d'apport",
        "number": "Facture n°",
        "period": "Période",
        "due": "Échéance",
        "from": "Émetteur (apporteur)",
        "to": "Destinataire (personne placée)",
        "client": "Au titre du placement chez",
        "item": "Désignation",
        "amount": "Montant",
        "lineItem": "Commission d'apport, échéance",
        "total": "Total à régler",
        "vat": "Montant hors taxes. Le régime de TVA dépend du statut de l'apporteur.",
        "footer": (
            "Document généré par Plugcut. Projet de démonstration, "
            "sans valeur comptable ni fiscale."
        ),
    },
    "en": {
        "title": "Referral commission invoice",
        "number": "Invoice no.",
        "period": "Period",
        "due": "Due",
        "from": "Issuer (referrer)",
        "to": "Recipient (placed person)",
        "client": "For the placement at",
        "item": "Description",
        "amount": "Amount",
        "lineItem": "Referral commission, installment",
        "total": "Total due",
        "vat": "Amount excluding tax. The VAT regime depends on the referrer's status.",
        "footer": "Generated by Plugcut. Demonstration project, no accounting or tax value.",
    },
}


def _money(value: Money) -> str:
    return f"{value.amount} {value.currency}"


class HtmlInvoiceRenderer:
    def render(
        self,
        referral: Referral,
        installment: CommissionInstallment,
        *,
        referrer_email: str,
        locale: str,
    ) -> str:
        labels = _LABELS.get(locale, _LABELS["en"])
        number = f"PLG-{str(referral.id)[:8].upper()}-{installment.sequence:02d}"
        period = f"{installment.period_start.isoformat()} / {installment.period_end.isoformat()}"
        amount = _money(installment.amount_due)
        designation = (
            f"{labels['lineItem']} {installment.sequence}/{referral.terms.duration_months}"
        )

        return f"""<!doctype html>
<html lang="{escape(locale)}">
<head>
<meta charset="utf-8" />
<title>{escape(labels['title'])} {escape(number)} - Plugcut</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; color: #16140f;
         max-width: 720px; margin: 2.5rem auto; padding: 0 1.5rem; line-height: 1.55; }}
  header {{ display: flex; justify-content: space-between; align-items: flex-start; }}
  .brand {{ font-weight: 700; letter-spacing: 0.05em; color: #6b7a00; }}
  h1 {{ font-size: 1.5rem; margin: 0.2rem 0 0; }}
  .num {{ font-family: ui-monospace, monospace; color: #555; }}
  .parties {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-top: 1.8rem; }}
  .parties h2 {{ font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.06em;
                 color: #888; margin: 0 0 0.3rem; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 1.8rem; }}
  th, td {{ text-align: left; padding: 0.7rem 0.6rem; border-bottom: 1px solid #ddd; }}
  th {{ font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.06em; color: #888; }}
  .num-col {{ text-align: right; font-family: ui-monospace, monospace; }}
  .total {{ font-weight: 700; font-size: 1.1rem; }}
  .vat {{ margin-top: 1rem; font-size: 0.82rem; color: #666; }}
  footer {{ margin-top: 2.5rem; font-size: 0.78rem; color: #999; }}
</style>
</head>
<body>
  <header>
    <div>
      <p class="brand">PLUGCUT</p>
      <h1>{escape(labels['title'])}</h1>
    </div>
    <div style="text-align:right">
      <div class="num">{escape(labels['number'])} {escape(number)}</div>
      <div class="num">{escape(labels['period'])} : {escape(period)}</div>
      <div class="num">{escape(labels['due'])} : {escape(installment.due_date.isoformat())}</div>
    </div>
  </header>

  <div class="parties">
    <div>
      <h2>{escape(labels['from'])}</h2>
      <div>{escape(referrer_email)}</div>
    </div>
    <div>
      <h2>{escape(labels['to'])}</h2>
      <div>{escape(referral.placed_person_email)}</div>
    </div>
  </div>

  <p style="margin-top:1.2rem;color:#666">
    {escape(labels['client'])} : {escape(referral.client_reference)}
  </p>

  <table>
    <thead>
      <tr><th>{escape(labels['item'])}</th><th class="num-col">{escape(labels['amount'])}</th></tr>
    </thead>
    <tbody>
      <tr><td>{escape(designation)}</td><td class="num-col">{escape(amount)}</td></tr>
      <tr><td class="total">{escape(labels['total'])}</td>
          <td class="num-col total">{escape(amount)}</td></tr>
    </tbody>
  </table>

  <p class="vat">{escape(labels['vat'])}</p>
  <footer>{escape(labels['footer'])}</footer>
</body>
</html>"""
