"""add invitation token and signatures to referrals

Revision ID: 18c7b92e6ab7
Revises: 657f4e241150
Create Date: 2026-06-30 12:12:40.452370

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18c7b92e6ab7'
down_revision: str | Sequence[str] | None = '657f4e241150'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('invitation_token', sa.String(length=64), nullable=True))
    op.add_column('referrals', sa.Column('referrer_signature', sa.String(length=120), nullable=True))
    op.add_column('referrals', sa.Column('placed_signature', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_referrals_invitation_token'), 'referrals', ['invitation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_invitation_token'), table_name='referrals')
    op.drop_column('referrals', 'placed_signature')
    op.drop_column('referrals', 'referrer_signature')
    op.drop_column('referrals', 'invitation_token')
    # ### end Alembic commands ###
