"""add dispute fields to referrals

Revision ID: 296de4d62569
Revises: edef8ad903b9
Create Date: 2026-06-30 18:13:40.726436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296de4d62569'
down_revision: Union[str, Sequence[str], None] = 'edef8ad903b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('disputed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('referrals', sa.Column('dispute_reason', sa.String(length=1000), nullable=True))
    op.add_column('referrals', sa.Column('disputed_by', sa.Uuid(), nullable=True))
    op.add_column('referrals', sa.Column('status_before_dispute', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'status_before_dispute')
    op.drop_column('referrals', 'disputed_by')
    op.drop_column('referrals', 'dispute_reason')
    op.drop_column('referrals', 'disputed_at')
    # ### end Alembic commands ###
