"""add last_reminded_at to commission_installments

Revision ID: 4c0f82d5c898
Revises: 296de4d62569
Create Date: 2026-06-30 18:36:04.735639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0f82d5c898'
down_revision: Union[str, Sequence[str], None] = '296de4d62569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_installments', sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_installments', 'last_reminded_at')
    # ### end Alembic commands ###
