"""add paid_at to commission_installments

Revision ID: d36469d2c83f
Revises: 18c7b92e6ab7
Create Date: 2026-06-30 13:47:30.135826

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd36469d2c83f'
down_revision: str | Sequence[str] | None = '18c7b92e6ab7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_installments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_installments', 'paid_at')
    # ### end Alembic commands ###
