"""Renders the referral agreement as a self-contained HTML document.

Pure string templating (no I/O), so it is trivially testable and could be piped to a
PDF engine later. Labels are localized FR/EN; all user-provided values are escaped.
"""

from __future__ import annotations

from html import escape

from app.domain.referrals.entities import Referral
from app.domain.shared.value_objects import Money

_LABELS: dict[str, dict[str, str]] = {
    "fr": {
        "title": "Accord d'apport d'affaires",
        "intro": "Le présent accord formalise la commission d'apport convenue entre les parties.",
        "referrer": "Apporteur",
        "placed": "Personne placée",
        "client": "Client (référence confidentielle)",
        "terms": "Conditions de commission",
        "dailyRate": "TJM placé",
        "commission": "Commission",
        "duration": "Durée",
        "months": "mois",
        "monthly": "Commission mensuelle estimée",
        "total": "Total estimé sur la durée",
        "attribution": "Preuve d'attribution",
        "attributionText": "Empreinte d'attribution scellée :",
        "signedOn": "Signé le",
        "footer": "Document généré par Plugcut. Projet de démonstration, sans valeur juridique.",
    },
    "en": {
        "title": "Referral agreement",
        "intro": "This agreement formalizes the referral commission agreed between the parties.",
        "referrer": "Referrer",
        "placed": "Placed person",
        "client": "Client (confidential reference)",
        "terms": "Commission terms",
        "dailyRate": "Placed day rate",
        "commission": "Commission",
        "duration": "Duration",
        "months": "months",
        "monthly": "Estimated monthly commission",
        "total": "Estimated total over the duration",
        "attribution": "Attribution proof",
        "attributionText": "Sealed attribution fingerprint:",
        "signedOn": "Signed on",
        "footer": "Generated by Plugcut. Demonstration project, no legal value.",
    },
}


def _money(value: Money) -> str:
    return f"{value.amount} {value.currency}"


class HtmlAgreementRenderer:
    def render(self, referral: Referral, *, referrer_email: str, locale: str) -> str:
        labels = _LABELS.get(locale, _LABELS["en"])
        terms = referral.terms
        monthly = terms.expected_amount_per_period
        total = monthly * terms.duration_months
        signed = (referral.accepted_by_placed_at or referral.created_at).date().isoformat()
        attribution = referral.attribution_hash or ""

        return f"""<!doctype html>
<html lang="{escape(locale)}">
<head>
<meta charset="utf-8" />
<title>{escape(labels['title'])} - Plugcut</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; color: #16140f;
         max-width: 720px; margin: 2.5rem auto; padding: 0 1.5rem; line-height: 1.55; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
  .brand {{ font-weight: 700; letter-spacing: 0.05em; color: #6b7a00; }}
  .intro {{ color: #555; }}
  h2 {{ font-size: 1.05rem; margin-top: 2rem; border-bottom: 1px solid #ddd;
        padding-bottom: 0.3rem; }}
  dl {{ display: grid; grid-template-columns: 1fr 1fr; gap: 0.4rem 1rem; }}
  dt {{ color: #666; }}
  dd {{ margin: 0; font-weight: 600; }}
  .hash {{ font-family: ui-monospace, monospace; word-break: break-all; font-size: 0.85rem;
           background: #f4f1ea; padding: 0.6rem 0.8rem; border-radius: 6px; }}
  footer {{ margin-top: 2.5rem; font-size: 0.78rem; color: #999; }}
</style>
</head>
<body>
  <p class="brand">PLUGCUT</p>
  <h1>{escape(labels['title'])}</h1>
  <p class="intro">{escape(labels['intro'])}</p>

  <h2>{escape(labels['referrer'])} &amp; {escape(labels['placed'])}</h2>
  <dl>
    <dt>{escape(labels['referrer'])}</dt><dd>{escape(referrer_email)}</dd>
    <dt>{escape(labels['placed'])}</dt><dd>{escape(referral.placed_person_email)}</dd>
    <dt>{escape(labels['client'])}</dt><dd>{escape(referral.client_reference)}</dd>
  </dl>

  <h2>{escape(labels['terms'])}</h2>
  <dl>
    <dt>{escape(labels['dailyRate'])}</dt><dd>{escape(_money(terms.daily_rate))}</dd>
    <dt>{escape(labels['commission'])}</dt><dd>{escape(str(terms.commission))}</dd>
    <dt>{escape(labels['duration'])}</dt>
    <dd>{terms.duration_months} {escape(labels['months'])}</dd>
    <dt>{escape(labels['monthly'])}</dt><dd>{escape(_money(monthly))}</dd>
    <dt>{escape(labels['total'])}</dt><dd>{escape(_money(total))}</dd>
  </dl>

  <h2>{escape(labels['attribution'])}</h2>
  <p>{escape(labels['attributionText'])}</p>
  <p class="hash">{escape(attribution)}</p>
  <p>{escape(labels['signedOn'])} {escape(signed)}</p>

  <footer>{escape(labels['footer'])}</footer>
</body>
</html>"""
